comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
- name: Codecov
  uses: codecov/codecov-action@v3.1.1
steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v3
  with:
    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    files: ./coverage1.xml,./coverage2.xml # optional
    flags: unittests # optional
    name: codecov-umbrella # optional
    fail_ci_if_error: true # optional (default = false)
    verbose: true # optional (default = false)
# The user that you will use to serve as the bot connection to Codecov
# This bot user must have permissions on the repo and Codecov (by logging in)

codecov:
  bot: <bot-username> #this is a username for Github/Gitlab/Bitbucket
